<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LSfF2plService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lSfF2pl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'access' => ['privates', 'App\\Service\\AccessHelper', 'getAccessHelperService', true],
            'weekLockRepo' => ['privates', 'App\\Repository\\PortalWeekLockRepository', 'getPortalWeekLockRepositoryService', true],
        ], [
            'em' => '?',
            'access' => 'App\\Service\\AccessHelper',
            'weekLockRepo' => 'App\\Repository\\PortalWeekLockRepository',
        ]);

        if (isset($container->privates['.service_locator.lSfF2pl'])) {
            return $container->privates['.service_locator.lSfF2pl'];
        }

        return $container->privates['.service_locator.lSfF2pl'] = $instance;
    }
}
