<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q9s2vYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q9s2v_Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q9s2v_Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'gps' => ['privates', 'App\\Service\\GooglePlacesService', 'getGooglePlacesServiceService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'gps' => 'App\\Service\\GooglePlacesService',
        ]);
    }
}
