<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YeW9PdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yeW9Pd_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doc' => ['privates', '.errored..service_locator.yeW9Pd_.App\\Entity\\PortalDocument', NULL, 'Cannot autowire service ".service_locator.yeW9Pd_": it needs an instance of "App\\Entity\\PortalDocument" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'doc' => 'App\\Entity\\PortalDocument',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.yeW9Pd_'])) {
            return $container->privates['.service_locator.yeW9Pd_'];
        }

        return $container->privates['.service_locator.yeW9Pd_'] = $instance;
    }
}
