<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P0XzHrbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p0XzHrb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'folder' => ['privates', '.errored..service_locator.p0XzHrb.App\\Entity\\PortalDocumentFolder', NULL, 'Cannot autowire service ".service_locator.p0XzHrb": it needs an instance of "App\\Entity\\PortalDocumentFolder" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'folder' => 'App\\Entity\\PortalDocumentFolder',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.p0XzHrb'])) {
            return $container->privates['.service_locator.p0XzHrb'];
        }

        return $container->privates['.service_locator.p0XzHrb'] = $instance;
    }
}
