<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LPaoYL6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lPaoYL6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'horaireRepo' => ['privates', 'App\\Repository\\PortalHoraireRepository', 'getPortalHoraireRepositoryService', true],
            'validationRepo' => ['privates', 'App\\Repository\\PortalMonthlyValidationRepository', 'getPortalMonthlyValidationRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'access' => ['privates', 'App\\Service\\AccessHelper', 'getAccessHelperService', true],
        ], [
            'horaireRepo' => 'App\\Repository\\PortalHoraireRepository',
            'validationRepo' => 'App\\Repository\\PortalMonthlyValidationRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
            'access' => 'App\\Service\\AccessHelper',
        ]);

        if (isset($container->privates['.service_locator.lPaoYL6'])) {
            return $container->privates['.service_locator.lPaoYL6'];
        }

        return $container->privates['.service_locator.lPaoYL6'] = $instance;
    }
}
