<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZK5xyIGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZK5xyIG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZK5xyIG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'item' => ['privates', '.errored..service_locator.ZK5xyIG.App\\Entity\\PortalProduct', NULL, 'Cannot autowire service ".service_locator.ZK5xyIG": it needs an instance of "App\\Entity\\PortalProduct" but this type has been excluded in "config/services.yaml".'],
        ], [
            'item' => 'App\\Entity\\PortalProduct',
        ]);
    }
}
