<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K3NKnI0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K3NKnI0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notifRepo' => ['privates', 'App\\Repository\\PortalNotificationRepository', 'getPortalNotificationRepositoryService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'notifRepo' => 'App\\Repository\\PortalNotificationRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.K3NKnI0'])) {
            return $container->privates['.service_locator.K3NKnI0'];
        }

        return $container->privates['.service_locator.K3NKnI0'] = $instance;
    }
}
