<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C63AksvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c63Aksv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'magasin' => ['privates', '.errored..service_locator.c63Aksv.App\\Entity\\Magasin', NULL, 'Cannot autowire service ".service_locator.c63Aksv": it needs an instance of "App\\Entity\\Magasin" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'magasin' => 'App\\Entity\\Magasin',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.c63Aksv'])) {
            return $container->privates['.service_locator.c63Aksv'];
        }

        return $container->privates['.service_locator.c63Aksv'] = $instance;
    }
}
