<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JqG0lt8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jqG0lt8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.jqG0lt8.App\\Entity\\PortalCategorieProduit', NULL, 'Cannot autowire service ".service_locator.jqG0lt8": it needs an instance of "App\\Entity\\PortalCategorieProduit" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'category' => 'App\\Entity\\PortalCategorieProduit',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.jqG0lt8'])) {
            return $container->privates['.service_locator.jqG0lt8'];
        }

        return $container->privates['.service_locator.jqG0lt8'] = $instance;
    }
}
