<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ztges6iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ztges6i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tour' => ['privates', '.errored..service_locator.ztges6i.App\\Entity\\TransEtLog', NULL, 'Cannot autowire service ".service_locator.ztges6i": it needs an instance of "App\\Entity\\TransEtLog" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'tour' => 'App\\Entity\\TransEtLog',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.ztges6i'])) {
            return $container->privates['.service_locator.ztges6i'];
        }

        return $container->privates['.service_locator.ztges6i'] = $instance;
    }
}
