<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J92g9LKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J92g9LK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.J92g9LK.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.J92g9LK": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.J92g9LK'])) {
            return $container->privates['.service_locator.J92g9LK'];
        }

        return $container->privates['.service_locator.J92g9LK'] = $instance;
    }
}
