<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hp2bPRiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hp2bPRi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'camion' => ['privates', '.errored..service_locator.Hp2bPRi.App\\Entity\\TransEtLogCamion', NULL, 'Cannot autowire service ".service_locator.Hp2bPRi": it needs an instance of "App\\Entity\\TransEtLogCamion" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'camion' => 'App\\Entity\\TransEtLogCamion',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.Hp2bPRi'])) {
            return $container->privates['.service_locator.Hp2bPRi'];
        }

        return $container->privates['.service_locator.Hp2bPRi'] = $instance;
    }
}
