<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessAdminControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iOCK5cN.App\Controller\Admin\AccessAdminController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'permRepo' => ['privates', 'App\\Repository\\ModulePermissionRepository', 'getModulePermissionRepositoryService', true],
            'roleRepo' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'permRepo' => 'App\\Repository\\ModulePermissionRepository',
            'roleRepo' => 'App\\Repository\\RoleRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\AccessAdminController::index()', $container);

        if (isset($container->privates['.service_locator.iOCK5cN.App\\Controller\\Admin\\AccessAdminController::index()'])) {
            return $container->privates['.service_locator.iOCK5cN.App\\Controller\\Admin\\AccessAdminController::index()'];
        }

        return $container->privates['.service_locator.iOCK5cN.App\\Controller\\Admin\\AccessAdminController::index()'] = $instance;
    }
}
