<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessAdminControlleraddRoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z0A7H.F.App\Controller\Admin\AccessAdminController::addRole()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.z0A7H.F'] ?? $container->load('get_ServiceLocator_Z0A7H_FService'));

        if (isset($container->privates['.service_locator.z0A7H.F.App\\Controller\\Admin\\AccessAdminController::addRole()'])) {
            return $container->privates['.service_locator.z0A7H.F.App\\Controller\\Admin\\AccessAdminController::addRole()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AccessAdminController::addRole()', $container);

        if (isset($container->privates['.service_locator.z0A7H.F.App\\Controller\\Admin\\AccessAdminController::addRole()'])) {
            return $container->privates['.service_locator.z0A7H.F.App\\Controller\\Admin\\AccessAdminController::addRole()'];
        }

        return $container->privates['.service_locator.z0A7H.F.App\\Controller\\Admin\\AccessAdminController::addRole()'] = $instance;
    }
}
