<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZdCTe2O.App\Controller\AgendaController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZdCTe2O.App\\Controller\\AgendaController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'horaireRepo' => ['privates', 'App\\Repository\\PortalHoraireRepository', 'getPortalHoraireRepositoryService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'horaireRepo' => 'App\\Repository\\PortalHoraireRepository',
        ]))->withContext('App\\Controller\\AgendaController::index()', $container);
    }
}
