<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaControllersaveEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..RoxwIY.App\Controller\AgendaController::saveEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'horaireRepo' => ['privates', 'App\\Repository\\PortalHoraireRepository', 'getPortalHoraireRepositoryService', true],
            'access' => ['privates', 'App\\Service\\AccessHelper', 'getAccessHelperService', true],
        ], [
            'em' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
            'horaireRepo' => 'App\\Repository\\PortalHoraireRepository',
            'access' => 'App\\Service\\AccessHelper',
        ]))->withContext('App\\Controller\\AgendaController::saveEvent()', $container);

        if (isset($container->privates['.service_locator..RoxwIY.App\\Controller\\AgendaController::saveEvent()'])) {
            return $container->privates['.service_locator..RoxwIY.App\\Controller\\AgendaController::saveEvent()'];
        }

        return $container->privates['.service_locator..RoxwIY.App\\Controller\\AgendaController::saveEvent()'] = $instance;
    }
}
