<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaControllerexportDetailedReportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XxoAGZC.App\Controller\AgendaController::exportDetailedReport()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.XxoAGZC'] ?? $container->load('get_ServiceLocator_XxoAGZCService'));

        if (isset($container->privates['.service_locator.XxoAGZC.App\\Controller\\AgendaController::exportDetailedReport()'])) {
            return $container->privates['.service_locator.XxoAGZC.App\\Controller\\AgendaController::exportDetailedReport()'];
        }

        $instance = $a->withContext('App\\Controller\\AgendaController::exportDetailedReport()', $container);

        if (isset($container->privates['.service_locator.XxoAGZC.App\\Controller\\AgendaController::exportDetailedReport()'])) {
            return $container->privates['.service_locator.XxoAGZC.App\\Controller\\AgendaController::exportDetailedReport()'];
        }

        return $container->privates['.service_locator.XxoAGZC.App\\Controller\\AgendaController::exportDetailedReport()'] = $instance;
    }
}
