<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaControllerupdateEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.glilSKZ.App\Controller\AgendaController::updateEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'horaire' => ['privates', '.errored..service_locator.glilSKZ.App\\Entity\\PortalHoraire', NULL, 'Cannot autowire service ".service_locator.glilSKZ": it needs an instance of "App\\Entity\\PortalHoraire" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'horaireRepo' => ['privates', 'App\\Repository\\PortalHoraireRepository', 'getPortalHoraireRepositoryService', true],
            'access' => ['privates', 'App\\Service\\AccessHelper', 'getAccessHelperService', true],
        ], [
            'horaire' => 'App\\Entity\\PortalHoraire',
            'em' => '?',
            'horaireRepo' => 'App\\Repository\\PortalHoraireRepository',
            'access' => 'App\\Service\\AccessHelper',
        ]))->withContext('App\\Controller\\AgendaController::updateEvent()', $container);

        if (isset($container->privates['.service_locator.glilSKZ.App\\Controller\\AgendaController::updateEvent()'])) {
            return $container->privates['.service_locator.glilSKZ.App\\Controller\\AgendaController::updateEvent()'];
        }

        return $container->privates['.service_locator.glilSKZ.App\\Controller\\AgendaController::updateEvent()'] = $instance;
    }
}
