<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessAdminControllereditRoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X55wFZd.App\Controller\Admin\AccessAdminController::editRole()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.X55wFZd'] ?? $container->load('get_ServiceLocator_X55wFZdService'));

        if (isset($container->privates['.service_locator.X55wFZd.App\\Controller\\Admin\\AccessAdminController::editRole()'])) {
            return $container->privates['.service_locator.X55wFZd.App\\Controller\\Admin\\AccessAdminController::editRole()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AccessAdminController::editRole()', $container);

        if (isset($container->privates['.service_locator.X55wFZd.App\\Controller\\Admin\\AccessAdminController::editRole()'])) {
            return $container->privates['.service_locator.X55wFZd.App\\Controller\\Admin\\AccessAdminController::editRole()'];
        }

        return $container->privates['.service_locator.X55wFZd.App\\Controller\\Admin\\AccessAdminController::editRole()'] = $instance;
    }
}
