<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AccessHelper' shared autowired service.
     *
     * @return \App\Service\AccessHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AccessHelper.php';

        $a = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['App\\Service\\AccessHelper'])) {
            return $container->privates['App\\Service\\AccessHelper'];
        }

        $instance = new \App\Service\AccessHelper($a, ($container->privates['App\\Repository\\ModulePermissionRepository'] ?? $container->load('getModulePermissionRepositoryService')));

        if (isset($container->privates['App\\Service\\AccessHelper'])) {
            return $container->privates['App\\Service\\AccessHelper'];
        }

        return $container->privates['App\\Service\\AccessHelper'] = $instance;
    }
}
