<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaControllerexportPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hm6ZVEx.App\Controller\AgendaController::exportPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hm6ZVEx.App\\Controller\\AgendaController::exportPdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'horaireRepo' => ['privates', 'App\\Repository\\PortalHoraireRepository', 'getPortalHoraireRepositoryService', true],
            'observationRepo' => ['privates', 'App\\Repository\\UserObservationRepository', 'getUserObservationRepositoryService', true],
        ], [
            'horaireRepo' => 'App\\Repository\\PortalHoraireRepository',
            'observationRepo' => 'App\\Repository\\UserObservationRepository',
        ]))->withContext('App\\Controller\\AgendaController::exportPdf()', $container);
    }
}
