<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessAdminControllerdeleteMagasinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c63Aksv.App\Controller\Admin\AccessAdminController::deleteMagasin()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.c63Aksv'] ?? $container->load('get_ServiceLocator_C63AksvService'));

        if (isset($container->privates['.service_locator.c63Aksv.App\\Controller\\Admin\\AccessAdminController::deleteMagasin()'])) {
            return $container->privates['.service_locator.c63Aksv.App\\Controller\\Admin\\AccessAdminController::deleteMagasin()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AccessAdminController::deleteMagasin()', $container);

        if (isset($container->privates['.service_locator.c63Aksv.App\\Controller\\Admin\\AccessAdminController::deleteMagasin()'])) {
            return $container->privates['.service_locator.c63Aksv.App\\Controller\\Admin\\AccessAdminController::deleteMagasin()'];
        }

        return $container->privates['.service_locator.c63Aksv.App\\Controller\\Admin\\AccessAdminController::deleteMagasin()'] = $instance;
    }
}
