<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AgendaController' shared autowired service.
     *
     * @return \App\Controller\AgendaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AgendaController.php';

        $container->services['App\\Controller\\AgendaController'] = $instance = new \App\Controller\AgendaController(($container->privates['App\\Service\\AccessHelper'] ?? $container->load('getAccessHelperService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\AgendaController', $container));

        return $instance;
    }
}
