<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaControllerupdateUserColorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.voEfSb7.App\Controller\AgendaController::updateUserColor()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.voEfSb7.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.voEfSb7": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'horaireRepo' => ['privates', 'App\\Repository\\PortalHoraireRepository', 'getPortalHoraireRepositoryService', true],
            'access' => ['privates', 'App\\Service\\AccessHelper', 'getAccessHelperService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'em' => '?',
            'horaireRepo' => 'App\\Repository\\PortalHoraireRepository',
            'access' => 'App\\Service\\AccessHelper',
        ]))->withContext('App\\Controller\\AgendaController::updateUserColor()', $container);

        if (isset($container->privates['.service_locator.voEfSb7.App\\Controller\\AgendaController::updateUserColor()'])) {
            return $container->privates['.service_locator.voEfSb7.App\\Controller\\AgendaController::updateUserColor()'];
        }

        return $container->privates['.service_locator.voEfSb7.App\\Controller\\AgendaController::updateUserColor()'] = $instance;
    }
}
