<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllercheckoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S0manwJ.App\Controller\CartController::checkout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'accessHelper' => ['privates', 'App\\Service\\AccessHelper', 'getAccessHelperService', true],
        ], [
            'em' => '?',
            'accessHelper' => 'App\\Service\\AccessHelper',
        ]))->withContext('App\\Controller\\CartController::checkout()', $container);

        if (isset($container->privates['.service_locator.S0manwJ.App\\Controller\\CartController::checkout()'])) {
            return $container->privates['.service_locator.S0manwJ.App\\Controller\\CartController::checkout()'];
        }

        return $container->privates['.service_locator.S0manwJ.App\\Controller\\CartController::checkout()'] = $instance;
    }
}
