<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2mnJRat.App\Controller\CartController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'item' => ['privates', '.errored..service_locator.2mnJRat.App\\Entity\\PortalProduct', NULL, 'Cannot autowire service ".service_locator.2mnJRat": it needs an instance of "App\\Entity\\PortalProduct" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'item' => 'App\\Entity\\PortalProduct',
            'em' => '?',
        ]))->withContext('App\\Controller\\CartController::update()', $container);

        if (isset($container->privates['.service_locator.2mnJRat.App\\Controller\\CartController::update()'])) {
            return $container->privates['.service_locator.2mnJRat.App\\Controller\\CartController::update()'];
        }

        return $container->privates['.service_locator.2mnJRat.App\\Controller\\CartController::update()'] = $instance;
    }
}
