<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientNumberGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ClientNumberGenerator' shared autowired service.
     *
     * @return \App\Service\ClientNumberGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ClientNumberGenerator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ClientNumberGenerator'])) {
            return $container->privates['App\\Service\\ClientNumberGenerator'];
        }

        $instance = new \App\Service\ClientNumberGenerator($a);

        if (isset($container->privates['App\\Service\\ClientNumberGenerator'])) {
            return $container->privates['App\\Service\\ClientNumberGenerator'];
        }

        return $container->privates['App\\Service\\ClientNumberGenerator'] = $instance;
    }
}
