<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeControllermyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OHw_Lh9.App\Controller\CommandeController::my()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.OHw_Lh9'] ?? $container->load('get_ServiceLocator_OHwLh9Service'));

        if (isset($container->privates['.service_locator.OHw_Lh9.App\\Controller\\CommandeController::my()'])) {
            return $container->privates['.service_locator.OHw_Lh9.App\\Controller\\CommandeController::my()'];
        }

        $instance = $a->withContext('App\\Controller\\CommandeController::my()', $container);

        if (isset($container->privates['.service_locator.OHw_Lh9.App\\Controller\\CommandeController::my()'])) {
            return $container->privates['.service_locator.OHw_Lh9.App\\Controller\\CommandeController::my()'];
        }

        return $container->privates['.service_locator.OHw_Lh9.App\\Controller\\CommandeController::my()'] = $instance;
    }
}
