<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleaningTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dgze84s.App\Entity\CleaningTask' shared service.
     *
     * @return \App\Entity\CleaningTask
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dgze84s": it needs an instance of "App\\Entity\\CleaningTask" but this type has been excluded in "config/services.yaml".');
    }
}
