<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateDefaultUsersCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateDefaultUsersCommand' shared autowired service.
     *
     * @return \App\Command\CreateDefaultUsersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateDefaultUsersCommand.php';

        $container->privates['App\\Command\\CreateDefaultUsersCommand'] = $instance = new \App\Command\CreateDefaultUsersCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:create-default-users');
        $instance->setDescription('Create default users for USER/EMPLOYE/ADMIN/MASTER_ADMIN/SUPER_ADMIN roles');

        return $instance;
    }
}
