<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateDefaultUsersCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateDefaultUsersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateDefaultUsersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-default-users', [], 'Create default users for USER/EMPLOYE/ADMIN/MASTER_ADMIN/SUPER_ADMIN roles', false, #[\Closure(name: 'App\\Command\\CreateDefaultUsersCommand')] fn (): \App\Command\CreateDefaultUsersCommand => ($container->privates['App\\Command\\CreateDefaultUsersCommand'] ?? $container->load('getCreateDefaultUsersCommandService')));
    }
}
