<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeAdminControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J92g9LK.App\Controller\Admin\CommandeAdminController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.J92g9LK'] ?? $container->load('get_ServiceLocator_J92g9LKService'));

        if (isset($container->privates['.service_locator.J92g9LK.App\\Controller\\Admin\\CommandeAdminController::show()'])) {
            return $container->privates['.service_locator.J92g9LK.App\\Controller\\Admin\\CommandeAdminController::show()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\CommandeAdminController::show()', $container);

        if (isset($container->privates['.service_locator.J92g9LK.App\\Controller\\Admin\\CommandeAdminController::show()'])) {
            return $container->privates['.service_locator.J92g9LK.App\\Controller\\Admin\\CommandeAdminController::show()'];
        }

        return $container->privates['.service_locator.J92g9LK.App\\Controller\\Admin\\CommandeAdminController::show()'] = $instance;
    }
}
