<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentFolderControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p0XzHrb.App\Controller\DocumentFolderController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.p0XzHrb'] ?? $container->load('get_ServiceLocator_P0XzHrbService'));

        if (isset($container->privates['.service_locator.p0XzHrb.App\\Controller\\DocumentFolderController::edit()'])) {
            return $container->privates['.service_locator.p0XzHrb.App\\Controller\\DocumentFolderController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\DocumentFolderController::edit()', $container);

        if (isset($container->privates['.service_locator.p0XzHrb.App\\Controller\\DocumentFolderController::edit()'])) {
            return $container->privates['.service_locator.p0XzHrb.App\\Controller\\DocumentFolderController::edit()'];
        }

        return $container->privates['.service_locator.p0XzHrb.App\\Controller\\DocumentFolderController::edit()'] = $instance;
    }
}
