<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseExceptionSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\DatabaseExceptionSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\DatabaseExceptionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/DatabaseExceptionSubscriber.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['App\\EventSubscriber\\DatabaseExceptionSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\DatabaseExceptionSubscriber'];
        }

        $instance = new \App\EventSubscriber\DatabaseExceptionSubscriber($a);

        if (isset($container->privates['App\\EventSubscriber\\DatabaseExceptionSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\DatabaseExceptionSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\DatabaseExceptionSubscriber'] = $instance;
    }
}
