<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f0YBYad.App\Controller\DocumentController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'document' => ['privates', '.errored..service_locator.f0YBYad.App\\Entity\\PortalDocument', NULL, 'Cannot autowire service ".service_locator.f0YBYad": it needs an instance of "App\\Entity\\PortalDocument" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'document' => 'App\\Entity\\PortalDocument',
            'entityManager' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\DocumentController::edit()', $container);

        if (isset($container->privates['.service_locator.f0YBYad.App\\Controller\\DocumentController::edit()'])) {
            return $container->privates['.service_locator.f0YBYad.App\\Controller\\DocumentController::edit()'];
        }

        return $container->privates['.service_locator.f0YBYad.App\\Controller\\DocumentController::edit()'] = $instance;
    }
}
