<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CrewJVm.App\Controller\DocumentController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CrewJVm.App\\Controller\\DocumentController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'documentRepository' => ['privates', 'App\\Repository\\PortalDocumentRepository', 'getPortalDocumentRepositoryService', true],
            'folderRepository' => ['privates', 'App\\Repository\\PortalDocumentFolderRepository', 'getPortalDocumentFolderRepositoryService', true],
        ], [
            'documentRepository' => 'App\\Repository\\PortalDocumentRepository',
            'folderRepository' => 'App\\Repository\\PortalDocumentFolderRepository',
        ]))->withContext('App\\Controller\\DocumentController::index()', $container);
    }
}
