<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Form\\Admin\\CommandeStatusType' => ['privates', 'App\\Form\\Admin\\CommandeStatusType', 'getCommandeStatusTypeService', true],
            'App\\Form\\Admin\\UserCreateType' => ['privates', 'App\\Form\\Admin\\UserCreateType', 'getUserCreateTypeService', true],
            'App\\Form\\Admin\\UserType' => ['privates', 'App\\Form\\Admin\\UserType', 'getUserTypeService', true],
            'App\\Form\\ChangePasswordType' => ['privates', 'App\\Form\\ChangePasswordType', 'getChangePasswordTypeService', true],
            'App\\Form\\CleaningTaskItemType' => ['privates', 'App\\Form\\CleaningTaskItemType', 'getCleaningTaskItemTypeService', true],
            'App\\Form\\CleaningTaskType' => ['privates', 'App\\Form\\CleaningTaskType', 'getCleaningTaskTypeService', true],
            'App\\Form\\CommandeItemType' => ['privates', 'App\\Form\\CommandeItemType', 'getCommandeItemTypeService', true],
            'App\\Form\\CommandeType' => ['privates', 'App\\Form\\CommandeType', 'getCommandeTypeService', true],
            'App\\Form\\PortalCategorieProduitType' => ['privates', 'App\\Form\\PortalCategorieProduitType', 'getPortalCategorieProduitTypeService', true],
            'App\\Form\\PortalDocumentFolderType' => ['privates', 'App\\Form\\PortalDocumentFolderType', 'getPortalDocumentFolderTypeService', true],
            'App\\Form\\PortalDocumentType' => ['privates', 'App\\Form\\PortalDocumentType', 'getPortalDocumentTypeService', true],
            'App\\Form\\PortalProductType' => ['privates', 'App\\Form\\PortalProductType', 'getPortalProductTypeService', true],
            'App\\Form\\RegistrationFormType' => ['privates', 'App\\Form\\RegistrationFormType', 'getRegistrationFormTypeService', true],
            'App\\Form\\TransEtLogCamionType' => ['privates', 'App\\Form\\TransEtLogCamionType', 'getTransEtLogCamionTypeService', true],
            'App\\Form\\TransEtLogType' => ['privates', 'App\\Form\\TransEtLogType', 'getTransEtLogTypeService', true],
            'App\\Form\\UserProfileType' => ['privates', 'App\\Form\\UserProfileType', 'getUserProfileTypeService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
        ], [
            'App\\Form\\Admin\\CommandeStatusType' => '?',
            'App\\Form\\Admin\\UserCreateType' => '?',
            'App\\Form\\Admin\\UserType' => '?',
            'App\\Form\\ChangePasswordType' => '?',
            'App\\Form\\CleaningTaskItemType' => '?',
            'App\\Form\\CleaningTaskType' => '?',
            'App\\Form\\CommandeItemType' => '?',
            'App\\Form\\CommandeType' => '?',
            'App\\Form\\PortalCategorieProduitType' => '?',
            'App\\Form\\PortalDocumentFolderType' => '?',
            'App\\Form\\PortalDocumentType' => '?',
            'App\\Form\\PortalProductType' => '?',
            'App\\Form\\RegistrationFormType' => '?',
            'App\\Form\\TransEtLogCamionType' => '?',
            'App\\Form\\TransEtLogType' => '?',
            'App\\Form\\UserProfileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.password_hasher'] ?? $container->load('getForm_TypeExtension_Form_PasswordHasherService'));
        }, 6), 'Symfony\\Component\\Form\\Flow\\Type\\FormFlowType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.flow.session_data_storage'] ?? $container->load('getForm_TypeExtension_Form_Flow_SessionDataStorageService'));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.password.password_hasher'] ?? $container->load('getForm_TypeExtension_Password_PasswordHasherService'));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.enum_type'] ??= new \Symfony\Component\Form\EnumFormTypeGuesser());
            yield 2 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 3))], new \Symfony\Component\Form\ResolvedFormTypeFactory());
    }
}
