<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeExtension_CsrfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.type_extension.csrf' shared service.
     *
     * @return \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Csrf/Type/FormTypeCsrfExtension.php';

        return $container->privates['form.type_extension.csrf'] = new \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension(($container->privates['security.csrf.same_origin_token_manager'] ?? self::getSecurity_Csrf_SameOriginTokenManagerService($container)), true, '_token', ($container->services['translator'] ?? self::getTranslatorService($container)), 'validators', ($container->privates['form.server_params'] ?? $container->load('getForm_ServerParamsService')), $container->parameters['form.type_extension.csrf.field_attr'], ['App\\Form\\Admin\\CommandeStatusType' => 'submit', 'App\\Form\\Admin\\UserCreateType' => 'submit', 'App\\Form\\Admin\\UserType' => 'submit', 'App\\Form\\ChangePasswordType' => 'submit', 'App\\Form\\CleaningTaskItemType' => 'submit', 'App\\Form\\CleaningTaskType' => 'submit', 'App\\Form\\CommandeItemType' => 'submit', 'App\\Form\\CommandeType' => 'submit', 'App\\Form\\PortalCategorieProduitType' => 'submit', 'App\\Form\\PortalDocumentFolderType' => 'submit', 'App\\Form\\PortalDocumentType' => 'submit', 'App\\Form\\PortalProductType' => 'submit', 'App\\Form\\RegistrationFormType' => 'submit', 'App\\Form\\TransEtLogCamionType' => 'submit', 'App\\Form\\TransEtLogType' => 'submit', 'App\\Form\\UserProfileType' => 'submit']);
    }
}
