<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGooglePlacesServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GooglePlacesService' shared autowired service.
     *
     * @return \App\Service\GooglePlacesService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GooglePlacesService.php';

        return $container->privates['App\\Service\\GooglePlacesService'] = new \App\Service\GooglePlacesService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GOOGLE_PLACES_API_KEY'));
    }
}
