<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLockHoursCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\LockHoursCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\LockHoursCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:lock-hours', [], 'Lock hours older than 6 weeks', false, #[\Closure(name: 'App\\Command\\LockHoursCommand')] fn (): \App\Command\LockHoursCommand => ($container->privates['App\\Command\\LockHoursCommand'] ?? $container->load('getLockHoursCommandService')));
    }
}
