<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLockHoursCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\LockHoursCommand' shared autowired service.
     *
     * @return \App\Command\LockHoursCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/LockHoursCommand.php';

        $container->privates['App\\Command\\LockHoursCommand'] = $instance = new \App\Command\LockHoursCommand(($container->privates['App\\Repository\\PortalHoraireRepository'] ?? $container->load('getPortalHoraireRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:lock-hours');
        $instance->setDescription('Lock hours older than 6 weeks');

        return $instance;
    }
}
