<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMagasinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c63Aksv.App\Entity\Magasin' shared service.
     *
     * @return \App\Entity\Magasin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.c63Aksv": it needs an instance of "App\\Entity\\Magasin" but this type has been excluded in "config/services.yaml".');
    }
}
