<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaintenanceControllersuiviService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qRHl.Q2.App\Controller\MaintenanceController::suivi()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taskRepo' => ['privates', 'App\\Repository\\CleaningTaskRepository', 'getCleaningTaskRepositoryService', true],
            'magasinRepo' => ['privates', 'App\\Repository\\MagasinRepository', 'getMagasinRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'taskRepo' => 'App\\Repository\\CleaningTaskRepository',
            'magasinRepo' => 'App\\Repository\\MagasinRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\MaintenanceController::suivi()', $container);

        if (isset($container->privates['.service_locator.qRHl.Q2.App\\Controller\\MaintenanceController::suivi()'])) {
            return $container->privates['.service_locator.qRHl.Q2.App\\Controller\\MaintenanceController::suivi()'];
        }

        return $container->privates['.service_locator.qRHl.Q2.App\\Controller\\MaintenanceController::suivi()'] = $instance;
    }
}
