<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaintenanceControllersuiviEditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dgze84s.App\Controller\MaintenanceController::suiviEdit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.dgze84s'] ?? $container->load('get_ServiceLocator_Dgze84sService'));

        if (isset($container->privates['.service_locator.dgze84s.App\\Controller\\MaintenanceController::suiviEdit()'])) {
            return $container->privates['.service_locator.dgze84s.App\\Controller\\MaintenanceController::suiviEdit()'];
        }

        $instance = $a->withContext('App\\Controller\\MaintenanceController::suiviEdit()', $container);

        if (isset($container->privates['.service_locator.dgze84s.App\\Controller\\MaintenanceController::suiviEdit()'])) {
            return $container->privates['.service_locator.dgze84s.App\\Controller\\MaintenanceController::suiviEdit()'];
        }

        return $container->privates['.service_locator.dgze84s.App\\Controller\\MaintenanceController::suiviEdit()'] = $instance;
    }
}
