<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaintenanceControllersuiviShowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gx0I.B6.App\Controller\MaintenanceController::suiviShow()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gx0I.B6.App\\Controller\\MaintenanceController::suiviShow()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'task' => ['privates', '.errored..service_locator.gx0I.B6.App\\Entity\\CleaningTask', NULL, 'Cannot autowire service ".service_locator.gx0I.B6": it needs an instance of "App\\Entity\\CleaningTask" but this type has been excluded in "config/services.yaml".'],
        ], [
            'task' => 'App\\Entity\\CleaningTask',
        ]))->withContext('App\\Controller\\MaintenanceController::suiviShow()', $container);
    }
}
