<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllermarkAllReadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K3NKnI0.App\Controller\NotificationController::markAllRead()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.K3NKnI0'] ?? $container->load('get_ServiceLocator_K3NKnI0Service'));

        if (isset($container->privates['.service_locator.K3NKnI0.App\\Controller\\NotificationController::markAllRead()'])) {
            return $container->privates['.service_locator.K3NKnI0.App\\Controller\\NotificationController::markAllRead()'];
        }

        $instance = $a->withContext('App\\Controller\\NotificationController::markAllRead()', $container);

        if (isset($container->privates['.service_locator.K3NKnI0.App\\Controller\\NotificationController::markAllRead()'])) {
            return $container->privates['.service_locator.K3NKnI0.App\\Controller\\NotificationController::markAllRead()'];
        }

        return $container->privates['.service_locator.K3NKnI0.App\\Controller\\NotificationController::markAllRead()'] = $instance;
    }
}
