<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllermarkSingleReadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.069IMqs.App\Controller\NotificationController::markSingleRead()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notification' => ['privates', '.errored..service_locator.069IMqs.App\\Entity\\PortalNotification', NULL, 'Cannot autowire service ".service_locator.069IMqs": it needs an instance of "App\\Entity\\PortalNotification" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'notification' => 'App\\Entity\\PortalNotification',
            'em' => '?',
        ]))->withContext('App\\Controller\\NotificationController::markSingleRead()', $container);

        if (isset($container->privates['.service_locator.069IMqs.App\\Controller\\NotificationController::markSingleRead()'])) {
            return $container->privates['.service_locator.069IMqs.App\\Controller\\NotificationController::markSingleRead()'];
        }

        return $container->privates['.service_locator.069IMqs.App\\Controller\\NotificationController::markSingleRead()'] = $instance;
    }
}
