<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4trujBo.App\Controller\NotificationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notifRepo' => ['privates', 'App\\Repository\\PortalNotificationRepository', 'getPortalNotificationRepositoryService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'notifRepo' => 'App\\Repository\\PortalNotificationRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\NotificationController::index()', $container);

        if (isset($container->privates['.service_locator.4trujBo.App\\Controller\\NotificationController::index()'])) {
            return $container->privates['.service_locator.4trujBo.App\\Controller\\NotificationController::index()'];
        }

        return $container->privates['.service_locator.4trujBo.App\\Controller\\NotificationController::index()'] = $instance;
    }
}
