<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.24Qf0r0.App\Controller\ProduitController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.24Qf0r0'] ?? $container->load('get_ServiceLocator_24Qf0r0Service'));

        if (isset($container->privates['.service_locator.24Qf0r0.App\\Controller\\ProduitController::new()'])) {
            return $container->privates['.service_locator.24Qf0r0.App\\Controller\\ProduitController::new()'];
        }

        $instance = $a->withContext('App\\Controller\\ProduitController::new()', $container);

        if (isset($container->privates['.service_locator.24Qf0r0.App\\Controller\\ProduitController::new()'])) {
            return $container->privates['.service_locator.24Qf0r0.App\\Controller\\ProduitController::new()'];
        }

        return $container->privates['.service_locator.24Qf0r0.App\\Controller\\ProduitController::new()'] = $instance;
    }
}
