<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalHoraireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O0AU02b.App\Entity\PortalHoraire' shared service.
     *
     * @return \App\Entity\PortalHoraire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O0AU02b": it needs an instance of "App\\Entity\\PortalHoraire" but this type has been excluded in "config/services.yaml".');
    }
}
