<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalDocumentControllerstreamDocumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9HHY6Wf.App\Controller\PortalDocumentController::streamDocument()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9HHY6Wf.App\\Controller\\PortalDocumentController::streamDocument()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doc' => ['privates', '.errored..service_locator.9HHY6Wf.App\\Entity\\PortalDocument', NULL, 'Cannot autowire service ".service_locator.9HHY6Wf": it needs an instance of "App\\Entity\\PortalDocument" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doc' => 'App\\Entity\\PortalDocument',
        ]))->withContext('App\\Controller\\PortalDocumentController::streamDocument()', $container);
    }
}
