<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalShortcut2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lQa63zQ.App\Entity\PortalShortcut' shared service.
     *
     * @return \App\Entity\PortalShortcut
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lQa63zQ": it needs an instance of "App\\Entity\\PortalShortcut" but this type has been excluded in "config/services.yaml".');
    }
}
