<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalMonthlyValidationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oMoJwLR.App\Entity\PortalMonthlyValidation' shared service.
     *
     * @return \App\Entity\PortalMonthlyValidation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oMoJwLR": it needs an instance of "App\\Entity\\PortalMonthlyValidation" but this type has been excluded in "config/services.yaml".');
    }
}
