<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalCategorieProduitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jqG0lt8.App\Entity\PortalCategorieProduit' shared service.
     *
     * @return \App\Entity\PortalCategorieProduit
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jqG0lt8": it needs an instance of "App\\Entity\\PortalCategorieProduit" but this type has been excluded in "config/services.yaml".');
    }
}
