<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalDocumentFolderTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PortalDocumentFolderType' shared autowired service.
     *
     * @return \App\Form\PortalDocumentFolderType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PortalDocumentFolderType.php';

        return $container->privates['App\\Form\\PortalDocumentFolderType'] = new \App\Form\PortalDocumentFolderType(($container->privates['App\\Repository\\RoleRepository'] ?? $container->load('getRoleRepositoryService')));
    }
}
