<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hgI1Jpn.App\Controller\ProduitController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hgI1Jpn.App\\Controller\\ProduitController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produit' => ['privates', '.errored..service_locator.hgI1Jpn.App\\Entity\\PortalProduct', NULL, 'Cannot autowire service ".service_locator.hgI1Jpn": it needs an instance of "App\\Entity\\PortalProduct" but this type has been excluded in "config/services.yaml".'],
        ], [
            'produit' => 'App\\Entity\\PortalProduct',
        ]))->withContext('App\\Controller\\ProduitController::show()', $container);
    }
}
