<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalDocumentControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lk_DycI.App\Controller\PortalDocumentController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'docRepo' => ['privates', 'App\\Repository\\PortalDocumentRepository', 'getPortalDocumentRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'docRepo' => 'App\\Repository\\PortalDocumentRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\PortalDocumentController::index()', $container);

        if (isset($container->privates['.service_locator.Lk_DycI.App\\Controller\\PortalDocumentController::index()'])) {
            return $container->privates['.service_locator.Lk_DycI.App\\Controller\\PortalDocumentController::index()'];
        }

        return $container->privates['.service_locator.Lk_DycI.App\\Controller\\PortalDocumentController::index()'] = $instance;
    }
}
