<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalDocument3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mDrVhZu.App\Entity\PortalDocument' shared service.
     *
     * @return \App\Entity\PortalDocument
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mDrVhZu": it needs an instance of "App\\Entity\\PortalDocument" but this type has been excluded in "config/services.yaml".');
    }
}
