<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalProductRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PortalProductRepository' shared autowired service.
     *
     * @return \App\Repository\PortalProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/PortalProductRepository.php';

        return $container->privates['App\\Repository\\PortalProductRepository'] = new \App\Repository\PortalProductRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
