<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitControllercategoryIndexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CAKnkfK.App\Controller\ProduitController::categoryIndex()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CAKnkfK.App\\Controller\\ProduitController::categoryIndex()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepo' => ['privates', 'App\\Repository\\PortalCategorieProduitRepository', 'getPortalCategorieProduitRepositoryService', true],
        ], [
            'categoryRepo' => 'App\\Repository\\PortalCategorieProduitRepository',
        ]))->withContext('App\\Controller\\ProduitController::categoryIndex()', $container);
    }
}
