<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xd7cjIp.App\Controller\ProduitController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepo' => ['privates', 'App\\Repository\\PortalProductRepository', 'getPortalProductRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'productRepo' => 'App\\Repository\\PortalProductRepository',
            'paginator' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\ProduitController::index()', $container);

        if (isset($container->privates['.service_locator.Xd7cjIp.App\\Controller\\ProduitController::index()'])) {
            return $container->privates['.service_locator.Xd7cjIp.App\\Controller\\ProduitController::index()'];
        }

        return $container->privates['.service_locator.Xd7cjIp.App\\Controller\\ProduitController::index()'] = $instance;
    }
}
