<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitControllercategoryEditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jqG0lt8.App\Controller\ProduitController::categoryEdit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.jqG0lt8'] ?? $container->load('get_ServiceLocator_JqG0lt8Service'));

        if (isset($container->privates['.service_locator.jqG0lt8.App\\Controller\\ProduitController::categoryEdit()'])) {
            return $container->privates['.service_locator.jqG0lt8.App\\Controller\\ProduitController::categoryEdit()'];
        }

        $instance = $a->withContext('App\\Controller\\ProduitController::categoryEdit()', $container);

        if (isset($container->privates['.service_locator.jqG0lt8.App\\Controller\\ProduitController::categoryEdit()'])) {
            return $container->privates['.service_locator.jqG0lt8.App\\Controller\\ProduitController::categoryEdit()'];
        }

        return $container->privates['.service_locator.jqG0lt8.App\\Controller\\ProduitController::categoryEdit()'] = $instance;
    }
}
