<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalDocumentControllersignService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yeW9Pd_.App\Controller\PortalDocumentController::sign()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.yeW9Pd_'] ?? $container->load('get_ServiceLocator_YeW9PdService'));

        if (isset($container->privates['.service_locator.yeW9Pd_.App\\Controller\\PortalDocumentController::sign()'])) {
            return $container->privates['.service_locator.yeW9Pd_.App\\Controller\\PortalDocumentController::sign()'];
        }

        $instance = $a->withContext('App\\Controller\\PortalDocumentController::sign()', $container);

        if (isset($container->privates['.service_locator.yeW9Pd_.App\\Controller\\PortalDocumentController::sign()'])) {
            return $container->privates['.service_locator.yeW9Pd_.App\\Controller\\PortalDocumentController::sign()'];
        }

        return $container->privates['.service_locator.yeW9Pd_.App\\Controller\\PortalDocumentController::sign()'] = $instance;
    }
}
