<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalConge3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ww.A.3g.App\Entity\PortalConge' shared service.
     *
     * @return \App\Entity\PortalConge
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ww.A.3g": it needs an instance of "App\\Entity\\PortalConge" but this type has been excluded in "config/services.yaml".');
    }
}
