<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortalDocumentRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PortalDocumentRepository' shared autowired service.
     *
     * @return \App\Repository\PortalDocumentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/PortalDocumentRepository.php';

        return $container->privates['App\\Repository\\PortalDocumentRepository'] = new \App\Repository\PortalDocumentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
