<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRHControllercongeDashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CUrOh.9.App\Controller\RHController::congeDashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'congeRepo' => ['privates', 'App\\Repository\\PortalCongeRepository', 'getPortalCongeRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'notifRepo' => ['privates', 'App\\Repository\\PortalNotificationRepository', 'getPortalNotificationRepositoryService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'congeRepo' => 'App\\Repository\\PortalCongeRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
            'notifRepo' => 'App\\Repository\\PortalNotificationRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\RHController::congeDashboard()', $container);

        if (isset($container->privates['.service_locator.CUrOh.9.App\\Controller\\RHController::congeDashboard()'])) {
            return $container->privates['.service_locator.CUrOh.9.App\\Controller\\RHController::congeDashboard()'];
        }

        return $container->privates['.service_locator.CUrOh.9.App\\Controller\\RHController::congeDashboard()'] = $instance;
    }
}
