<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRHControllercheckReportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lPaoYL6.App\Controller\RHController::checkReport()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.lPaoYL6'] ?? $container->load('get_ServiceLocator_LPaoYL6Service'));

        if (isset($container->privates['.service_locator.lPaoYL6.App\\Controller\\RHController::checkReport()'])) {
            return $container->privates['.service_locator.lPaoYL6.App\\Controller\\RHController::checkReport()'];
        }

        $instance = $a->withContext('App\\Controller\\RHController::checkReport()', $container);

        if (isset($container->privates['.service_locator.lPaoYL6.App\\Controller\\RHController::checkReport()'])) {
            return $container->privates['.service_locator.lPaoYL6.App\\Controller\\RHController::checkReport()'];
        }

        return $container->privates['.service_locator.lPaoYL6.App\\Controller\\RHController::checkReport()'] = $instance;
    }
}
