<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRHControllercongePrintToolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BcuvBg3.App\Controller\RHController::congePrintTool()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BcuvBg3.App\\Controller\\RHController::congePrintTool()'] = ($container->privates['.service_locator.BcuvBg3'] ?? $container->load('get_ServiceLocator_BcuvBg3Service'))->withContext('App\\Controller\\RHController::congePrintTool()', $container);
    }
}
