<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\RoleRepository' shared autowired service.
     *
     * @return \App\Repository\RoleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/RoleRepository.php';

        return $container->privates['App\\Repository\\RoleRepository'] = new \App\Repository\RoleRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
