<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRHControllerresetValidationSignatureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T6axquL.App\Controller\RHController::resetValidationSignature()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'validationRepo' => ['privates', 'App\\Repository\\PortalMonthlyValidationRepository', 'getPortalMonthlyValidationRepositoryService', true],
            'horaireRepo' => ['privates', 'App\\Repository\\PortalHoraireRepository', 'getPortalHoraireRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'access' => ['privates', 'App\\Service\\AccessHelper', 'getAccessHelperService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'validationRepo' => 'App\\Repository\\PortalMonthlyValidationRepository',
            'horaireRepo' => 'App\\Repository\\PortalHoraireRepository',
            'em' => '?',
            'access' => 'App\\Service\\AccessHelper',
        ]))->withContext('App\\Controller\\RHController::resetValidationSignature()', $container);

        if (isset($container->privates['.service_locator.T6axquL.App\\Controller\\RHController::resetValidationSignature()'])) {
            return $container->privates['.service_locator.T6axquL.App\\Controller\\RHController::resetValidationSignature()'];
        }

        return $container->privates['.service_locator.T6axquL.App\\Controller\\RHController::resetValidationSignature()'] = $instance;
    }
}
