<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRHControllercongeGeneratePdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JIT0FUz.App\Controller\RHController::congeGeneratePdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JIT0FUz.App\\Controller\\RHController::congeGeneratePdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conge' => ['privates', '.errored..service_locator.JIT0FUz.App\\Entity\\PortalConge', NULL, 'Cannot autowire service ".service_locator.JIT0FUz": it needs an instance of "App\\Entity\\PortalConge" but this type has been excluded in "config/services.yaml".'],
        ], [
            'conge' => 'App\\Entity\\PortalConge',
        ]))->withContext('App\\Controller\\RHController::congeGeneratePdf()', $container);
    }
}
