<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRHControllerdownloadPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oMoJwLR.App\Controller\RHController::downloadPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oMoJwLR.App\\Controller\\RHController::downloadPdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'validation' => ['privates', '.errored..service_locator.oMoJwLR.App\\Entity\\PortalMonthlyValidation', NULL, 'Cannot autowire service ".service_locator.oMoJwLR": it needs an instance of "App\\Entity\\PortalMonthlyValidation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'validation' => 'App\\Entity\\PortalMonthlyValidation',
        ]))->withContext('App\\Controller\\RHController::downloadPdf()', $container);
    }
}
