<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRHControlleradminCongeActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ww.A.3g.App\Controller\RHController::adminCongeAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conge' => ['privates', '.errored..service_locator.Ww.A.3g.App\\Entity\\PortalConge', NULL, 'Cannot autowire service ".service_locator.Ww.A.3g": it needs an instance of "App\\Entity\\PortalConge" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'horaireRepo' => ['privates', 'App\\Repository\\PortalHoraireRepository', 'getPortalHoraireRepositoryService', true],
        ], [
            'conge' => 'App\\Entity\\PortalConge',
            'em' => '?',
            'horaireRepo' => 'App\\Repository\\PortalHoraireRepository',
        ]))->withContext('App\\Controller\\RHController::adminCongeAction()', $container);

        if (isset($container->privates['.service_locator.Ww.A.3g.App\\Controller\\RHController::adminCongeAction()'])) {
            return $container->privates['.service_locator.Ww.A.3g.App\\Controller\\RHController::adminCongeAction()'];
        }

        return $container->privates['.service_locator.Ww.A.3g.App\\Controller\\RHController::adminCongeAction()'] = $instance;
    }
}
