<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRHControlleremployeeCongeActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J2PoNal.App\Controller\RHController::employeeCongeAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conge' => ['privates', '.errored..service_locator.J2PoNal.App\\Entity\\PortalConge', NULL, 'Cannot autowire service ".service_locator.J2PoNal": it needs an instance of "App\\Entity\\PortalConge" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'conge' => 'App\\Entity\\PortalConge',
            'em' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\RHController::employeeCongeAction()', $container);

        if (isset($container->privates['.service_locator.J2PoNal.App\\Controller\\RHController::employeeCongeAction()'])) {
            return $container->privates['.service_locator.J2PoNal.App\\Controller\\RHController::employeeCongeAction()'];
        }

        return $container->privates['.service_locator.J2PoNal.App\\Controller\\RHController::employeeCongeAction()'] = $instance;
    }
}
