<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaticPageControllersaranService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q9s2v_Y.App\Controller\StaticPageController::saran()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q9s2v_Y.App\\Controller\\StaticPageController::saran()'] = ($container->privates['.service_locator.Q9s2v_Y'] ?? $container->load('get_ServiceLocator_Q9s2vYService'))->withContext('App\\Controller\\StaticPageController::saran()', $container);
    }
}
