<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShortcutControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lQa63zQ.App\Controller\Admin\ShortcutController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'shortcut' => ['privates', '.errored..service_locator.lQa63zQ.App\\Entity\\PortalShortcut', NULL, 'Cannot autowire service ".service_locator.lQa63zQ": it needs an instance of "App\\Entity\\PortalShortcut" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'shortcut' => 'App\\Entity\\PortalShortcut',
            'em' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\Admin\\ShortcutController::edit()', $container);

        if (isset($container->privates['.service_locator.lQa63zQ.App\\Controller\\Admin\\ShortcutController::edit()'])) {
            return $container->privates['.service_locator.lQa63zQ.App\\Controller\\Admin\\ShortcutController::edit()'];
        }

        return $container->privates['.service_locator.lQa63zQ.App\\Controller\\Admin\\ShortcutController::edit()'] = $instance;
    }
}
