<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedBulkUsersCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SeedBulkUsersCommand' shared autowired service.
     *
     * @return \App\Command\SeedBulkUsersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SeedBulkUsersCommand.php';

        $container->privates['App\\Command\\SeedBulkUsersCommand'] = $instance = new \App\Command\SeedBulkUsersCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:seed-bulk-users');
        $instance->setDescription('Seed 5 accounts for every role (bulk operation)');

        return $instance;
    }
}
