<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShortcutControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uG2CAfN.App\Controller\Admin\ShortcutController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uG2CAfN.App\\Controller\\Admin\\ShortcutController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\PortalShortcutRepository', 'getPortalShortcutRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\PortalShortcutRepository',
        ]))->withContext('App\\Controller\\Admin\\ShortcutController::index()', $container);
    }
}
