<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedBulkUsersCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SeedBulkUsersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SeedBulkUsersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:seed-bulk-users', [], 'Seed 5 accounts for every role (bulk operation)', false, #[\Closure(name: 'App\\Command\\SeedBulkUsersCommand')] fn (): \App\Command\SeedBulkUsersCommand => ($container->privates['App\\Command\\SeedBulkUsersCommand'] ?? $container->load('getSeedBulkUsersCommandService')));
    }
}
