<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportLogistiqueControllercamionDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hp2bPRi.App\Controller\TransportLogistiqueController::camionDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Hp2bPRi'] ?? $container->load('get_ServiceLocator_Hp2bPRiService'));

        if (isset($container->privates['.service_locator.Hp2bPRi.App\\Controller\\TransportLogistiqueController::camionDelete()'])) {
            return $container->privates['.service_locator.Hp2bPRi.App\\Controller\\TransportLogistiqueController::camionDelete()'];
        }

        $instance = $a->withContext('App\\Controller\\TransportLogistiqueController::camionDelete()', $container);

        if (isset($container->privates['.service_locator.Hp2bPRi.App\\Controller\\TransportLogistiqueController::camionDelete()'])) {
            return $container->privates['.service_locator.Hp2bPRi.App\\Controller\\TransportLogistiqueController::camionDelete()'];
        }

        return $container->privates['.service_locator.Hp2bPRi.App\\Controller\\TransportLogistiqueController::camionDelete()'] = $instance;
    }
}
