<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransEtLogRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TransEtLogRepository' shared autowired service.
     *
     * @return \App\Repository\TransEtLogRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/TransEtLogRepository.php';

        return $container->privates['App\\Repository\\TransEtLogRepository'] = new \App\Repository\TransEtLogRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
