<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportLogistiqueControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..AvqRiZ.App\Controller\TransportLogistiqueController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tourRepo' => ['privates', 'App\\Repository\\TransEtLogRepository', 'getTransEtLogRepositoryService', true],
            'camionRepo' => ['privates', 'App\\Repository\\TransEtLogCamionRepository', 'getTransEtLogCamionRepositoryService', true],
            'magasinRepo' => ['privates', 'App\\Repository\\MagasinRepository', 'getMagasinRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'tourRepo' => 'App\\Repository\\TransEtLogRepository',
            'camionRepo' => 'App\\Repository\\TransEtLogCamionRepository',
            'magasinRepo' => 'App\\Repository\\MagasinRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\TransportLogistiqueController::index()', $container);

        if (isset($container->privates['.service_locator..AvqRiZ.App\\Controller\\TransportLogistiqueController::index()'])) {
            return $container->privates['.service_locator..AvqRiZ.App\\Controller\\TransportLogistiqueController::index()'];
        }

        return $container->privates['.service_locator..AvqRiZ.App\\Controller\\TransportLogistiqueController::index()'] = $instance;
    }
}
