<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportLogistiqueControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ztges6i.App\Controller\TransportLogistiqueController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ztges6i'] ?? $container->load('get_ServiceLocator_Ztges6iService'));

        if (isset($container->privates['.service_locator.ztges6i.App\\Controller\\TransportLogistiqueController::edit()'])) {
            return $container->privates['.service_locator.ztges6i.App\\Controller\\TransportLogistiqueController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\TransportLogistiqueController::edit()', $container);

        if (isset($container->privates['.service_locator.ztges6i.App\\Controller\\TransportLogistiqueController::edit()'])) {
            return $container->privates['.service_locator.ztges6i.App\\Controller\\TransportLogistiqueController::edit()'];
        }

        return $container->privates['.service_locator.ztges6i.App\\Controller\\TransportLogistiqueController::edit()'] = $instance;
    }
}
