<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportLogistiqueControllercamionIndexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._mqdUQj.App\Controller\TransportLogistiqueController::camionIndex()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._mqdUQj.App\\Controller\\TransportLogistiqueController::camionIndex()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'camionRepo' => ['privates', 'App\\Repository\\TransEtLogCamionRepository', 'getTransEtLogCamionRepositoryService', true],
        ], [
            'camionRepo' => 'App\\Repository\\TransEtLogCamionRepository',
        ]))->withContext('App\\Controller\\TransportLogistiqueController::camionIndex()', $container);
    }
}
