<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransEtLogService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ztges6i.App\Entity\TransEtLog' shared service.
     *
     * @return \App\Entity\TransEtLog
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ztges6i": it needs an instance of "App\\Entity\\TransEtLog" but this type has been excluded in "config/services.yaml".');
    }
}
