<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportLogistiqueControllerreportPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ay5J5Zn.App\Controller\TransportLogistiqueController::reportPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ay5J5Zn.App\\Controller\\TransportLogistiqueController::reportPdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tourRepo' => ['privates', 'App\\Repository\\TransEtLogRepository', 'getTransEtLogRepositoryService', true],
            'camionRepo' => ['privates', 'App\\Repository\\TransEtLogCamionRepository', 'getTransEtLogCamionRepositoryService', true],
        ], [
            'tourRepo' => 'App\\Repository\\TransEtLogRepository',
            'camionRepo' => 'App\\Repository\\TransEtLogCamionRepository',
        ]))->withContext('App\\Controller\\TransportLogistiqueController::reportPdf()', $container);
    }
}
