<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserObservationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZDkct_7.App\Controller\UserObservationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'observation' => ['privates', '.errored..service_locator.ZDkct_7.App\\Entity\\UserObservation', NULL, 'Cannot autowire service ".service_locator.ZDkct_7": it needs an instance of "App\\Entity\\UserObservation" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'observation' => 'App\\Entity\\UserObservation',
            'em' => '?',
        ]))->withContext('App\\Controller\\UserObservationController::delete()', $container);

        if (isset($container->privates['.service_locator.ZDkct_7.App\\Controller\\UserObservationController::delete()'])) {
            return $container->privates['.service_locator.ZDkct_7.App\\Controller\\UserObservationController::delete()'];
        }

        return $container->privates['.service_locator.ZDkct_7.App\\Controller\\UserObservationController::delete()'] = $instance;
    }
}
