<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q.9q_tU.App\Controller\Admin\UserAdminController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.q.9q_tU'] ?? $container->load('get_ServiceLocator_Q_9qTUService'));

        if (isset($container->privates['.service_locator.q.9q_tU.App\\Controller\\Admin\\UserAdminController::delete()'])) {
            return $container->privates['.service_locator.q.9q_tU.App\\Controller\\Admin\\UserAdminController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\UserAdminController::delete()', $container);

        if (isset($container->privates['.service_locator.q.9q_tU.App\\Controller\\Admin\\UserAdminController::delete()'])) {
            return $container->privates['.service_locator.q.9q_tU.App\\Controller\\Admin\\UserAdminController::delete()'];
        }

        return $container->privates['.service_locator.q.9q_tU.App\\Controller\\Admin\\UserAdminController::delete()'] = $instance;
    }
}
