<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserObservationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UserObservationController' shared autowired service.
     *
     * @return \App\Controller\UserObservationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UserObservationController.php';

        $container->services['App\\Controller\\UserObservationController'] = $instance = new \App\Controller\UserObservationController(($container->privates['App\\Service\\AccessHelper'] ?? $container->load('getAccessHelperService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\UserObservationController', $container));

        return $instance;
    }
}
