<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GVRSIXQ.App\Controller\Admin\UserAdminController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.GVRSIXQ.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.GVRSIXQ": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'em' => '?',
            'passwordHasher' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\Admin\\UserAdminController::edit()', $container);

        if (isset($container->privates['.service_locator.GVRSIXQ.App\\Controller\\Admin\\UserAdminController::edit()'])) {
            return $container->privates['.service_locator.GVRSIXQ.App\\Controller\\Admin\\UserAdminController::edit()'];
        }

        return $container->privates['.service_locator.GVRSIXQ.App\\Controller\\Admin\\UserAdminController::edit()'] = $instance;
    }
}
