<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserObservationControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bsOaCd7.App\Controller\UserObservationController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'observationRepo' => ['privates', 'App\\Repository\\UserObservationRepository', 'getUserObservationRepositoryService', true],
            'lockRepo' => ['privates', 'App\\Repository\\ObservationMonthLockRepository', 'getObservationMonthLockRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'observationRepo' => 'App\\Repository\\UserObservationRepository',
            'lockRepo' => 'App\\Repository\\ObservationMonthLockRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\UserObservationController::update()', $container);

        if (isset($container->privates['.service_locator.bsOaCd7.App\\Controller\\UserObservationController::update()'])) {
            return $container->privates['.service_locator.bsOaCd7.App\\Controller\\UserObservationController::update()'];
        }

        return $container->privates['.service_locator.bsOaCd7.App\\Controller\\UserObservationController::update()'] = $instance;
    }
}
