<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserObservationControllercheckLockService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xbRDjLo.App\Controller\UserObservationController::checkLock()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xbRDjLo.App\\Controller\\UserObservationController::checkLock()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lockRepo' => ['privates', 'App\\Repository\\ObservationMonthLockRepository', 'getObservationMonthLockRepositoryService', true],
        ], [
            'lockRepo' => 'App\\Repository\\ObservationMonthLockRepository',
        ]))->withContext('App\\Controller\\UserObservationController::checkLock()', $container);
    }
}
