<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserObservationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PpbGjOz.App\Controller\UserObservationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PpbGjOz.App\\Controller\\UserObservationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'observationRepo' => ['privates', 'App\\Repository\\UserObservationRepository', 'getUserObservationRepositoryService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'observationRepo' => 'App\\Repository\\UserObservationRepository',
        ]))->withContext('App\\Controller\\UserObservationController::index()', $container);
    }
}
