<?php

namespace ContainerKDcOObg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserObservationControllertoggleLockService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rWkFeCb.App\Controller\UserObservationController::toggleLock()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lockRepo' => ['privates', 'App\\Repository\\ObservationMonthLockRepository', 'getObservationMonthLockRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'lockRepo' => 'App\\Repository\\ObservationMonthLockRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\UserObservationController::toggleLock()', $container);

        if (isset($container->privates['.service_locator.rWkFeCb.App\\Controller\\UserObservationController::toggleLock()'])) {
            return $container->privates['.service_locator.rWkFeCb.App\\Controller\\UserObservationController::toggleLock()'];
        }

        return $container->privates['.service_locator.rWkFeCb.App\\Controller\\UserObservationController::toggleLock()'] = $instance;
    }
}
