[ec2]
lsj-prod ansible_host=35.180.116.20 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/lsj-ec2-key.pem

[ec2:vars]
# Variables injectées via ansible-vault ou CLI --extra-vars
github_user=ArmSal
# mysql_root_password  → stocker dans ansible-vault
# mysql_password       → stocker dans ansible-vault
# grafana_admin_password → stocker dans ansible-vault
# ghcr_token           → stocker dans ansible-vault
