<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKDcOObg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKDcOObg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKDcOObg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKDcOObg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKDcOObg\App_KernelDevDebugContainer([
    'container.build_hash' => 'KDcOObg',
    'container.build_id' => 'd921e7b4',
    'container.build_time' => 1777552515,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKDcOObg');
