route:
  receiver: 'discord_webhook'
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: 'discord_webhook'
    discord_configs:
      - webhook_url_file: '/etc/alertmanager/discord_webhook_url'
