# infra/monitoring/alert_rules.yml

groups:
  - name: LSDJ_Alerts
    rules:
      # CPU > 80%
      - alert: HostHighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "CPU utilisé à plus de 80% sur {{ $labels.instance }}"

      # Disk > 90%
      - alert: HostOutOfDiskSpace
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Espace disque critique (< 10% libre) sur {{ $labels.instance }}"

      # PHP Latency > 2s
      - alert: PhpFpmHighRequestDuration
        expr: php_fpm_request_duration_seconds > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Temps de réponse PHP-FPM supérieur à 2 secondes"
